version: '3'

volumes:
  pg_data_production:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    image: mrazzzlop/foodgram_backend
    env_file: .env
    volumes:
      - static:/static_backend/
      - media:/media_files/
    depends_on:
      - db

  frontend:
    image: mrazzzlop/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
    depends_on:
      - backend

  nginx:
    image: mrazzzlop/foodgram_nginx
    env_file: .env
    volumes:
      - static:/static_backend/
      - media:/media_files/
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend
