version: '3'

volumes:
  pg_data_production:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file:
      - ./.env
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    image: mrazzzlop/foodgram_backend
    env_file:
      - ./.env
    volumes:
      - static:/static_backend/
      - media:/media_files/
    depends_on:
      - db
    restart: always

  nginx:
    image: mrazzzlop/foodgram_nginx
    env_file:
      - ./.env
    volumes:
      - /etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - static:/static_backend/
      - media:/media_files/
    ports:
      - 8000:80
    restart: always
    depends_on:
      - backend
