version: '3.3'

volumes:
  pg_data:
  static:
  media:
  redoc:
services:
  db:
    image: postgres:16
    restart: always
    env_file: .env.example
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ../backend/
    depends_on:
      - db
    env_file: .env.example
    volumes:
      - static:/static_backend
      - media:/media_files
      - redoc:/app/api/docs/
  nginx:
    build: ../nginx/
    ports:
      - "80:80"
    volumes:
      - media:/var/html/media/
      - static:/var/html/static/
      - redoc:/usr/share/nginx/html/api/docs/
