PAGE_SIZE_PAGINATORS = 6

(
    INGREGIENT_NAME_MAX_LENGTH,
    INGREGIENT_MEASUREMENT_UNIT_NAME_MAX_LENGTH,
    TAG_NAME_LENGTH,
    TAG_SLUG_LENGTH,
    RECIPE_NAME_LENGTH
) = [200 for _ in range(5)]

COOKING_TIME_MIN_VALUE = AMOUNT_MIN_VALUE = 1
COOKING_TIME_MAX_VALUE = AMOUNT_MAХ_VALUE = 32000

(
    FIRST_NAME_MAX_LENGTH,
    LAST_NAME_MAX_LENGTH,
    USERNAME_MAX_LENGTH,
    PASSWORD_MAX_LENGTH
) = [150 for _ in range(4)]
